services:
  api-gateway:
    build:
      context: ./src/Api.Gateway
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    networks:
      - internal-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080

  order-api:
    build:
      context: ./src/Order.Api
      dockerfile: Dockerfile
    ports:
      - "9001:8081"
    networks:
      - internal-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8081

  product-api:
    build:
      context: ./src/Product.Api
      dockerfile: Dockerfile
    ports:
      - "9002:8082"
    networks:
      - internal-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8082

  rating-api:
    build:
      context: ./src/Rating.Api
      dockerfile: Dockerfile
    ports:
      - "9003:8083"
    networks:
      - internal-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8083

  user-api:
    build:
      context: ./src/User.Api
      dockerfile: Dockerfile
    ports:
      - "9004:8084"
    networks:
      - internal-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8084

networks:
  internal-network:
    name: internal-network
    driver: bridge