@url = http://localhost:8080/api/users
#@url = http://localhost:5070

### Register User
POST {{url}}/register
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "securepassword123"
}

###

### Login User
POST {{url}}/login
Content-Type: application/json

{
  "email": "nejmlesz@gmail.com",
  "password": "securepassword123"
}

###