---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: microservices
  labels:
    HealthChecks: enabled
spec:
  selector:
    app: order-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
