---
apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: microservices
  labels:
    HealthChecks: enabled
spec:
  selector:
    app: product-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
