---
apiVersion: v1
kind: Service
metadata:
  name: rating-api
  namespace: microservices
  labels:
    HealthChecks: enabled
spec:
  selector:
    app: rating-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: ClusterIP
