---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: user.api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8084"
          volumeMounts:
            - name: appsettings-production-volume
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
      volumes:
        - name: appsettings-production-volume
          configMap:
            name: microservices-config
      restartPolicy: Always
