---
apiVersion: v1
kind: Service
metadata:
  name: user-api
  namespace: microservices
  labels:
    HealthChecks: enabled
spec:
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP
